CREATE ROLE SVCollaborator IN ROLE Client;

CREATE USER legoblin
	WITH BYPASSRLS
	PASSWORD NULL
	IN ROLE SVCollaborator;
CREATE USER adrioh
	WITH BYPASSRLS
	PASSWORD NULL
	IN ROLE SVCollaborator;
CREATE USER "Ryan Heuvel"
	WITH BYPASSRLS
	PASSWORD NULL
	IN ROLE SVCollaborator;
CREATE USER "Ndeye659"
	WITH BYPASSRLS
	PASSWORD NULL
	IN ROLE SVCollaborator;
CREATE USER "Sokhnafaty09"
	WITH BYPASSRLS
	PASSWORD NULL
	IN ROLE SVCollaborator;

CREATE DATABASE ShallowView OWNER SVCollaborator;
REVOKE ALL PRIVILEGES ON DATABASE ShallowView FROM PUBLIC;
GRANT ALL PRIVILEGES ON DATABASE ShallowView TO SVCollaborator, Admin;

CREATE DATABASE ShallowViewAnalysis OWNER SVCollaborator;
REVOKE ALL PRIVILEGES ON DATABASE ShallowView FROM PUBLIC;
GRANT ALL PRIVILEGES ON DATABASE ShallowView TO SVCollaborator, Admin;